import { Button } from "@/components/ui/button"
import { ArrowLeft } from "lucide-react"
import Link from "next/link"

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-teal-900 to-slate-900">
      <div className="container mx-auto px-6 py-12 max-w-4xl">
        <div className="mb-8">
          <Button variant="ghost" className="text-white hover:bg-white/10 mb-4" asChild>
            <Link href="/">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Home
            </Link>
          </Button>
          <h1 className="text-4xl font-bold text-white mb-4">Terms of Service</h1>
          <p className="text-gray-300">Last updated: July 25, 2025</p>
        </div>

        <div className="prose prose-invert prose-lg max-w-none">
          <div className="bg-white/5 border border-white/10 rounded-lg p-8 backdrop-blur-sm space-y-8">
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">1. Introduction</h2>
              <p className="text-gray-300 leading-relaxed">
                Welcome to TabTub (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). TabTub is a browser extension designed to help you manage your browser tabs efficiently. These Terms of Service (&quot;Terms&quot;) govern your use of the TabTub extension and its related services (collectively, the &quot;Service&quot;).
              </p>
              <p className="text-gray-300 leading-relaxed">
                By installing and using TabTub, you agree to be bound by these Terms. If you do not agree to these Terms, do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
              <p className="text-gray-300 leading-relaxed">
                TabTub provides a suite of tools for tab management. The Service is provided as a browser extension and all your data is stored locally on your device.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">3. Privacy and Data</h2>
              <p className="text-gray-300 leading-relaxed">
                We are committed to your privacy. As stated in our Privacy Policy, TabTub operates entirely on your local device. We do not collect, store, or transmit any of your personal data, browsing history, or tab information. All data generated by the extension remains in your browser&apos;s local storage.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">4. Intellectual Property</h2>
              <p className="text-gray-300 leading-relaxed">
                TabTub is a free and open-source project. The source code is available on GitHub and is licensed under the MIT License. You are free to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software, subject to the conditions of the MIT License.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">5. User Conduct</h2>
              <p className="text-gray-300 leading-relaxed">
                You agree not to use the Service for any purpose that is illegal or prohibited by these Terms. You agree not to:
              </p>
              <ul className="list-disc list-inside text-gray-300 mt-2 space-y-1">
                <li>Decompile, reverse engineer, or otherwise attempt to obtain the source code of the Service, other than as permitted by the open-source license.</li>
                <li>Use the Service in any manner that could damage, disable, overburden, or impair the Service or interfere with any other party&apos;s use of the Service.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">6. Disclaimer of Warranties</h2>
              <p className="text-gray-300 leading-relaxed">
                The Service is provided &quot;as is&quot; and &quot;as available&quot; without any warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or secure. You use the Service at your own risk.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">7. Limitation of Liability</h2>
              <p className="text-gray-300 leading-relaxed">
                To the fullest extent permitted by law, in no event shall we be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from your use of the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">8. Changes to These Terms</h2>
              <p className="text-gray-300 leading-relaxed">
                We may modify these Terms from time to time. We will notify you of any changes by posting the new Terms on this page. You are advised to review these Terms periodically for any changes. Changes to these Terms are effective when they are posted on this page.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">9. Contact Us</h2>
              <p className="text-gray-300 leading-relaxed">
                If you have any questions about these Terms, please send us a message by going to the Contact Us menu.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}